### ISSUE TITLE
Safari IOS and MacOS. Unexpected private name #validate. 

### ISSUE THREAD

**Issue by timmeade** [kelseykm/vcard4#1]
I am getting the following on safari IOS and MacOS

Unhandled Runtime Error
SyntaxError: Unexpected private name #validate. Cannot parse class method with private name.

```
./node_modules/vcard4/src/esm/values.js

file:///Users/tim/src/active/.next/static/chunks/pages/v1/%5Bsource%5D/%5Btapid%5D.js (4525:5)
```

NextJS 11.   Works fine on Chrome and Firefox.

Any ideas?

Thanks

Tim

**Comment by timmeade** [comment]
i removed the .next folder and let it rebuild. 

No changes. still same error.

**Comment by kelseykm** [comment]
Hello Tim,

I would like to help, but you haven't provided enough information. 
Could you post the entire stack trace of the error you're getting?

**Comment by timmeade** [comment]
Full stack from safari on macos

```
Call Stack
eval

[native code]
./node_modules/vcard4/src/esm/values.js

file:///Users/tim/src/active/do.dev/app.contacts.dev/.next/static/chunks/pages/v1/%5Bsource%5D/%5Btapid%5D.js (4525:5)
<unknown>

/_next/static/chunks/webpack.js (685:35)
__webpack_require__

file:///Users/tim/src/active/do.dev/app.contacts.dev/.next/static/chunks/webpack.js (37:37)
eval

[native code]
./node_modules/vcard4/index.js

/_next/static/chunks/pages/v1/%5Bsource%5D/%5Btapid%5D.js (4459:5)
<unknown>

file:///Users/tim/src/active/do.dev/app.contacts.dev/.next/static/chunks/webpack.js (685:35)
__webpack_require__

/_next/static/chunks/webpack.js (37:37)
eval

[native code]
./components/LandingPage/index.tsx

file:///Users/tim/src/active/do.dev/app.contacts.dev/.next/static/chunks/pages/v1/%5Bsource%5D/%5Btapid%5D.js (3219:5)
<unknown>

/_next/static/chunks/webpack.js (685:35)
__webpack_require__

file:///Users/tim/src/active/do.dev/app.contacts.dev/.next/static/chunks/webpack.js (37:37)
eval

[native code]
./pages/v1/[source]/[tapid].tsx

/_next/static/chunks/pages/v1/%5Bsource%5D/%5Btapid%5D.js (3593:5)
<unknown>

file:///Users/tim/src/active/do.dev/app.contacts.dev/.next/static/chunks/webpack.js (685:35)
__webpack_require__

/_next/static/chunks/webpack.js (37:37)
promiseReactionJob

[native code]
```

**Comment by timmeade** [comment]
I removed all the '#' for the private names in both the esm and cjs files.

Then removed the .next folder from nextjs.

Let it all rebuild and things are working on safari now.   I'm doing further testing.    Also not sure what the private removals may cause for issues.

**Comment by kelseykm** [comment]
https://caniuse.com/?search=private%20class

🤦 Apparently, Safari supports private class fields but not private class method. Gonna put a warning on the README...

I recommend using Babel

**Comment by timmeade** [comment]
Ok i have a fix.... 

using this npm [next-transpile-modules](https://www.npmjs.com/package/next-transpile-modules). it can transpile this code to work.

Also need to add to next.config.js for nextjs. here is mine.
 
```
const withTM = require('next-transpile-modules')(['vcard4']); // pass the modules you would like to see transpiled

const withPlugins = require('next-compose-plugins');
const nextConfig = {
  images: {
    domains: ['firebasestorage.googleapis.com', 'res.cloudinary.com'],
  },
};

module.exports = withPlugins([withTM], nextConfig);
```

Appears to work after all this.   Onwards.
