### ISSUE TITLE
Does not support property groups

### ISSUE THREAD

**Issue by MarcelWaldvogel** [kelseykm/vcard4#10]
At least the parser only seems to support [property groups](https://datatracker.ietf.org/doc/html/rfc6350#section-3.3) by having it return a parameter name with a dot in it; delegating the support entirely to calling code.

**Comment by kelseykm** [comment]
Please clarify what you mean.

**Comment by MarcelWaldvogel** [comment]
The explanation of property groups in RFC6350:

> The [property] group construct is used to group related properties together. The group name is a syntactic convention used to indicate that all property names prefaced with the same group name SHOULD be grouped together when displayed by an application.  It has no other significance.  Implementations that do not understand or support grouping MAY simply strip off any text before a "." to the left of the type name and present the types and values as normal.

It is e.g. used for grouping properties where e.g., `TYPE=home|work` is not powerful enough. Here is an example where a person has two different work numbers:

```vcard
BEGIN:VCARD
VERSION:4.0
FN:Jane Doe
1.ORG;TYPE=work:ACME\, Inc.
1.TEL;TYPE=work:+1 234 555 0000
2.ORG;TYPE=work:Roadrunner\, Inc.
2.TEL;TYPE=work:+1 999 555 0000
END:VCARD
```

**Comment by kelseykm** [comment]
Oh...had missed that part. I'll work on it.

**Comment by MarcelWaldvogel** [comment]
In the simplest case, just drop things up to the first dot, as the RFC suggests.

**Comment by kelseykm** [comment]
> In the simplest case, just drop things up to the first dot, as the RFC suggests.

Yeah, that's what I've decided to do because the parser is not made with an intention of displaying anything to an end-user but to aid in programmatically accessing vCard properties and values

**Comment by kelseykm** [comment]
FIXED

**Comment by kelseykm** [comment]
Fully supported as from v3.0.0, in both parsing and generating.
