### ISSUE TITLE
No support for escaped backslashes in parser

### ISSUE THREAD

**Issue by MarcelWaldvogel** [kelseykm/vcard4#11]
Fields ending in (properly escaped) backslashes will cause the field delimiter to be ignored. E.g.

```vcard
NICKNAME:Backslash\\,The weird guy
```
should result in two value strings, `Backslash\` and `The weird guy`. However, it will be parsed as `Backslash\,The weird guy`, due to the look-back logic.

Yes, this is probably rare/a constructed case. And yes, it is hard to implement with your current parser logic.

(I'm fine with several of my issues being closed as WONTFIX; I just noticed them while reading RFC6350.)

**Comment by kelseykm** [comment]
> Fields ending in (properly escaped) backslashes will cause the field delimiter to be ignored. E.g.
> 
> ```
> NICKNAME:Backslash\\,The weird guy
> ```
> 
> should result in two value strings, `Backslash\` and `The weird guy`. However, it will be parsed as `Backslash\,The weird guy`, due to the look-back logic.

This is actually correct behaviour, because ```\\``` is actually one ```\``` and so you're just escaping the comma, not the backslash. But I get what you mean. 

> Yes, this is probably rare/a constructed case. And yes, it is hard to implement with your current parser logic.

It's actually quite easy with the current logic...

**Comment by kelseykm** [comment]
>  it is hard to implement with your current parser logic.

It's actually quite easy with the current logic. I'll fix it in the next patch release.

**Comment by MarcelWaldvogel** [comment]
Looking forward to this. You'll add a `hasAnOddNumberOfBackslashesBefore()` function?

**Comment by kelseykm** [comment]
> > it is hard to implement with your current parser logic.
> 
> It's actually quite easy with the current logic. I'll fix it in the next patch release.

I take it back...it's not as easy as I had imagined...

**Comment by kelseykm** [comment]
> Looking forward to this. You'll add a `hasAnOddNumberOfBackslashesBefore()` function?

With the way the parser is currently written, I've found adding a separate function for that complicates things

**Comment by kelseykm** [comment]
> Looking forward to this. You'll add a `hasAnOddNumberOfBackslashesBefore()` function?

I've done something like that.

Now fixed!
