### ISSUE TITLE
Support parsing multiple vCards in a single file

### ISSUE THREAD

**Issue by MarcelWaldvogel** [kelseykm/vcard4#4]
[RFC6350 6.1.1 BEGIN](https://datatracker.ietf.org/doc/html/rfc6350#section-6.1.1) says:

> [The BEGIN property] is provided for applications that wish to define content that can contain multiple entities within the same text/vcard content-type […]

I understand this as "there might be multiple vCard entities in a single file. Be prepared". This is also supported by several address books exporting multiple entries as a single vCard file.

A minimalistic way (besides delegating the entire work to the caller) would be to [exit the loop after reading an `END` property](https://github.com/kelseykm/vcard4/blob/6762ec3855/src/esm/parse.js#L303) and return the unparsed remainder of the file to the caller.

**Comment by kelseykm** [comment]
This feature will be added in the next minor release.

**Comment by yashgada** [comment]
Is this added yet?

**Comment by kelseykm** [comment]
yes
