### ISSUE TITLE
"npm run test" fails due to private class fields

### ISSUE THREAD

**Issue by MarcelWaldvogel** [kelseykm/vcard4#7]
Environment: Ubuntu 21.10 (node v12.22.5)

```sh
git checkout https://github.com/keseykm/vcard4.git
cd vcard4
npm i
npm run test
```

results in

```
> vcard4@2.0.3 test
> mocha

/home/marcel/Repos/vcard4/src/cjs/values.js:38
  #validate(textValue) {
           ^

SyntaxError: Unexpected token '('
[…]
```

Running `npm -D i node`, i.e., updating to node 17.0.1 for the repository, fixes this. However, as the installed node 12.22.5 should already support this feature by default, I doubt that this is the best fix.

**Comment by kelseykm** [comment]
Looks like Node 12 didn't support private class methods just private class fields, so this issue doesn't really belong here 🙂.

Anyway, I think updating node really is the best fix. As of October 2021, Node 14 is the LTS version and Node 17 is the current version.

**Comment by MarcelWaldvogel** [comment]
I understand that `devDependencies` is the wrong place, indeed. But how about `engines`?

```json
"engines": {
  "node": ">=14"
}
```

(And not just because the Ubuntu version released this month is still on Node 12. In fact, it would generally reduce the possibility to result in an invalid deployment.)

**Comment by kelseykm** [comment]
> I understand that `devDependencies` is the wrong place, indeed. But how about `engines`?
> 
> ```json
> "engines": {
>   "node": ">=14"
> }
> ```
> 
> (And not just because the Ubuntu version released this month is still on Node 12. In fact, it would generally reduce the possibility to result in an invalid deployment.)

Good idea.
