### ISSUE TITLE
Accept bare newlines as well

### ISSUE THREAD

**Issue by MarcelWaldvogel** [kelseykm/vcard4#8]
To support the IETF's general [Robustness principle](https://en.wikipedia.org/wiki/Robustness_principle), I would recommend to accept bare newlines as well on parsing. However, I would also understand if you wanted to remain tight on what input you wanted to accept.

**Comment by kelseykm** [comment]
The robustness principle is a good one to keep in mind for most cases but I feel that on major/foundational areas of a specification, no compromise should be made because it tends to harm more than help.
I place line delimiting in that category, along with the charset.
